# _config.yml
title: MongoMan
description: A modern, web-based MongoDB admin interface
baseurl: "/mongoman"
url: ""
github_username: AienTech

# Build settings
remote_theme: just-the-docs/just-the-docs
source: doc

# Theme settings
search_enabled: true
heading_anchors: true
color_scheme: light

# Just the Docs settings
aux_links:
  "MongoMan on GitHub":
    - "https://github.com/AienTech/mongoman"

callouts:
  warning:
    title: Warning
    color: yellow
  note:
    title: Note
    color: blue

# Navigation
nav_external_links:
  - title: View on GitHub
    url: https://github.com/AienTech/mongoman
    hide_icon: false