# Site settings
title: MongoMan
description: A modern, web-based MongoDB admin interface
baseurl: '/mongoman'
url: ''
repository: AienTech/mongoman

# Theme settings
remote_theme: just-the-docs/just-the-docs
source: docs

# Build settings
markdown: kramdown
sass:
  style: compressed
  sass_dir: _sass

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-feed

# Just the Docs settings
color_scheme: light
search_enabled: true
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  'MongoMan on GitHub':
    - 'https://github.com/AienTech/mongoman'
aux_links_new_tab: true

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
